pub enum Tile {
    None = 0,

    YiWan    = 1 << 0,
    LiangWan = 1 << 1,
    SanWan   = 1 << 2,
    SiWan    = 1 << 3,
    WuWan    = 1 << 4,
    RedWan   = 1 << 5,
    GoldWan  = 1 << 6,
    LiuWan   = 1 << 7,
    QiWan    = 1 << 8,
    BaWan    = 1 << 9,
    JiuWan   = 1 << 10,

    YiTong    = 1 << 11,
    LiangTong = 1 << 12,
    SanTong   = 1 << 13,
    SiTong    = 1 << 14,
    WuTong    = 1 << 15,
    RedTong   = 1 << 16,
    GoldTong  = 1 << 17,
    LiuTong   = 1 << 18,
    QiTong    = 1 << 19,
    BaTong    = 1 << 20,
    JiuTong   = 1 << 21,

    YiSuo    = 1 << 22,
    LiangSuo = 1 << 23,
    SanSuo   = 1 << 24,
    SiSuo    = 1 << 25,
    WuSuo    = 1 << 26,
    RedSuo   = 1 << 27,
    GoldSuo  = 1 << 28,
    LiuSuo   = 1 << 29,
    QiSuo    = 1 << 30,
    BaSuo    = 1 << 31,
    JiuSuo   = 1 << 32,

    East  = 1 << 33,
    North = 1 << 34,
    West  = 1 << 35,
    South = 1 << 36,

    White = 1 << 37,
    Green = 1 << 38,
    Red   = 1 << 39,
}

pub const fn tile_display(tile: Tile) -> &'static str {
    match tile {
        Tile::None => "None",

        Tile::YiWan    => "C1",
        Tile::LiangWan => "C2",
        Tile::SanWan   => "C3",
        Tile::SiWan    => "C4",
        Tile::WuWan    => "C5",
        Tile::RedWan   => "CR",
        Tile::GoldWan  => "CG",
        Tile::LiuWan   => "C6",
        Tile::QiWan    => "C7",
        Tile::BaWan    => "C8",
        Tile::JiuWan   => "C9",

        Tile::YiTong    => "D1",
        Tile::LiangTong => "D2",
        Tile::SanTong   => "D3",
        Tile::SiTong    => "D4",
        Tile::WuTong    => "D5",
        Tile::RedTong   => "DR",
        Tile::GoldTong  => "DG",
        Tile::LiuTong   => "D6",
        Tile::QiTong    => "D7",
        Tile::BaTong    => "D8",
        Tile::JiuTong   => "D9",

        Tile::YiSuo    => "B1",
        Tile::LiangSuo => "B2",
        Tile::SanSuo   => "B3",
        Tile::SiSuo    => "B4",
        Tile::WuSuo    => "B5",
        Tile::RedSuo   => "BR",
        Tile::GoldSuo  => "BG",
        Tile::LiuSuo   => "B6",
        Tile::QiSuo    => "B7",
        Tile::BaSuo    => "B8",
        Tile::JiuSuo   => "B9",

        Tile::East  => "WE",
        Tile::South => "WS",
        Tile::West  => "WW",
        Tile::North => "WN",

        Tile::White => "SW",
        Tile::Green => "SG",
        Tile::Red   => "SR",
    }
}